### ISSUE TITLE
Atmega 32 pinout

### ISSUE THREAD

**Issue by lmeucchi** [felias-fogg/RescueAVR#3]
Hi! How are you?
I have an atmega32 and I think it is locked.I do not know if I can unlock it by programming with hvpp, if it is true, how is the wiring connection?
Thank you greetings

**Comment by felias-fogg** [comment]
It's easy. Just google "atmega32". This will give a link to the Atmega32 data sheet. On page 259, you will find the pin mapping for HVPP.

**Comment by lmeucchi** [comment]
I think I forgot to see the datasheet jajajaja
There is everything you need to know.Thank you very much for answering, today I am going to try to unlock it.Greetings
