### ISSUE TITLE
RescueAVR

### ISSUE THREAD

**Issue by whynot2018** [felias-fogg/RescueAVR#6]
hi
Is it possible to utilize RescueAVR 32pin atmega328p-au? I made an adapter for 28 atmega328p. 
![RescueAVR](https://github.com/felias-fogg/RescueAVR/assets/48062504/284d1e52-54ac-485b-b273-d6171cede456)
best regards

**Comment by felias-fogg** [comment]
Sure! Just have a look at the ATmega328P datasheet (https://ww1.microchip.com/downloads/aemDocuments/documents/MCU08/ProductDocuments/DataSheets/ATmega48A-PA-88A-PA-168A-PA-328-P-DS-DS40002061B.pdf), Section 28.6 on parallel programming.

**Comment by whynot2018** [comment]
Sorry but I don't get it? It's pretty complicated. I have only two digital pins left and I need to add PC[1:0]:PB[5:0]-DATA 
PC1
PC0
PB5
PB4
PB3
PB2
PB1
PB0

https://github.com/felias-fogg/RescueAVR/blob/master/RescueAVR-megaX8_breadboard.png
https://images.prismic.io/circuito/8e3a980f0f964cc539b4cbbba2654bb660db6f52_arduino-uno-pinout-diagram.png?auto=compress,format


ATmega328pSMD 	ARDUINO PRO MINI	Function               ARDUINO UNO
	Pin		               PIN	                               	                       PIN
	1-PD3		       3	    			        WRi     		       A2
	2-PD4		       4	  	  	                BS1     		       A1
	3-GND		       GND         			GND	               GND
	4-VCC		       VCC         			VCC	               12
	5-GND		       GND         			GND         	        GND
	6-VCC		       VCC         			VCC         		12
	7-PB6		       (Q1 CYSTIAL PIN3)        XTAL1   	                A0
	8-PB7		       (Q1 CYSTIAL PIN1)        -     	  		         -
	9-PD5		       5	            	               XA0                          10
	10-PD6		       6	            	               XA1                          11
	11-PD7		       7	            	               PAGEL                     GND
	12-PB0		       8	          	               DATA0	                9
	13-PB1		       9	             	               DATA1	                8
	14-PB2	  	      10 	      	    	               DATA2  	                7
	15-PB3		      11        	  		       DATA3    		        6
	16-PB4		      12        			       DATA4    		        5
	17-PB5		      13	        		       DATA5        	        4
	18-AVCC	       VCC	                               VCC                         12
	19-ADC6               A6	         	               -             		       -				
	20-AREF		      -			               -              		       -		
	21-GND		      GND		  	              GND		               GND		
	22-ADC7	      A7		  	               -	                      -				
	23-PC0		      A0        		  	      DATA6	              3		
	24-PC1		      A1		          	      DATA7	      	      2		
	25-PC2		      A2	        	  	      BS2                         A5		
	26-PC3		      A3		           	      -		             -		
	27-PC4		      A4		                      -	                     -		
	28-PC5		      A5		  	             -                               -		
	29-PC6		      RESET		            RESET                    AVR-RST
	30-PD0		      RT1	  	         	    -		                   -
	31-PD1		      TX0		  	            RDY		           A4		
	32-PD2		      2	            	  	    OEi 			   A3



![Screenshot from 2024-01-29 23-48-07](https://github.com/felias-fogg/RescueAVR/assets/48062504/71d3d5e7-9ef9-43dc-950f-b50ea4eba21e)
![Screenshot from 2024-01-29 23-48-13](https://github.com/felias-fogg/RescueAVR/assets/48062504/3d76d1c4-7d4e-427b-b78b-e11e2203d6e6)
![Screenshot from 2024-01-30 10-08-23](https://github.com/felias-fogg/RescueAVR/assets/48062504/82cad115-e1f2-4cf6-94bd-95de7c4338c6)

**Comment by felias-fogg** [comment]
Hi,

it is pretty complicated! And with the new AVR chips they pretty much simplified it. 

However, your table already shows the correct mapping. DATA0-DATA5 are on PB0-PB5 and DATA6-DATA7 are on PC0-PC1. And they are connected to the right Arduino pins (on which the RescueAVR chip is supposed to run). So, nothing to worry.

**Comment by felias-fogg** [comment]
Cool! Tell me, when you successfully reset the chips!
